# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
  export ZSH=/home/alessio/.oh-my-zsh

# Path for python & AWS CLI
  export PATH=~/.local/bin:$PATH

# Path for GO
  # GOROOT is the location where Go package is installed on your system.
  export GOROOT=/usr/local/go
  # GOPATH is the location of your work directory
  export GOPATH=$HOME/go
  # PATH variable to access go binary system wide
  export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes

# Set list of themes to load
# Set list of themes to load
# Setting this variable when ZSH_THEME=random

# select theme
ZSH_THEME="powerlevel9k/powerlevel9k"

# cause zsh load theme from this variable instead of
# looking in ~/.oh-my-zsh/themes/
# An empty array have no effect
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  solarized-man
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# kubectl autocompletion
source <(kubectl completion zsh)

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias lg=git

# enable nerdfonts
POWERLEVEL9K_MODE='nerdfont-complete'

# segments on the left prompt
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user background_jobs dir_writable dir vcs status)
# disable right prompt
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# leave three directories at the end
POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
# nice to have but impossible to read :-)
#POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"

# display a lock icon for directories where you can't write
POWERLEVEL9K_DIR_SHOW_WRITABLE="true"

# disable status segment when last command completes ok
POWERLEVEL9K_STATUS_OK="false"

# Advanced `vcs` color customization
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='051'
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='031'

POWERLEVEL9K_VCS_CLEAN_FOREGROUND='249'
POWERLEVEL9K_VCS_CLEAN_BACKGROUND='235'

POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='249'
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND='235'

POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='249'
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND='235'

POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='007'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='237'

POWERLEVEL9K_DIR_HOME_FOREGROUND='007'
POWERLEVEL9K_DIR_HOME_BACKGROUND='237'

POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='007'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='237'

POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND='015'
POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND='001'
